-- =========================================
-- Chinook Music Store SQL Analysis Project
-- =========================================

-- 1. List all customers from India
SELECT *
FROM Customer
WHERE Country = 'India';

-- 2. Total revenue generated by the store
SELECT SUM(Total) AS TotalRevenue
FROM Invoice;

-- 3. Total revenue by country
SELECT BillingCountry, SUM(Total) AS Revenue
FROM Invoice
GROUP BY BillingCountry
ORDER BY Revenue DESC;

-- 4. Top 5 customers by total spending
SELECT 
    c.CustomerId,
    c.FirstName,
    c.LastName,
    SUM(i.Total) AS TotalSpent
FROM Customer c
JOIN Invoice i
ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId
ORDER BY TotalSpent DESC
LIMIT 5;

-- 5. Top 5 selling tracks
SELECT 
    t.Name,
    SUM(il.Quantity) AS TotalSold
FROM InvoiceLine il
JOIN Track t
ON il.TrackId = t.TrackId
GROUP BY t.TrackId
ORDER BY TotalSold DESC
LIMIT 5;

-- 6. Customers who spent more than average customer spending (Subquery)
SELECT 
    FirstName,
    LastName
FROM Customer
WHERE CustomerId IN (
    SELECT CustomerId
    FROM Invoice
    GROUP BY CustomerId
    HAVING SUM(Total) > (
        SELECT AVG(Total)
        FROM Invoice
    )
);

-- 7. Rank customers based on total spending (Window Function)
SELECT 
    c.CustomerId,
    c.FirstName,
    c.LastName,
    SUM(i.Total) AS TotalSpent,
    RANK() OVER (ORDER BY SUM(i.Total) DESC) AS SpendingRank
FROM Customer c
JOIN Invoice i
ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId;

-- 8. Top artist by revenue (CTE)
WITH ArtistRevenue AS (
    SELECT 
        ar.ArtistId,
        ar.Name AS ArtistName,
        SUM(il.UnitPrice * il.Quantity) AS Revenue
    FROM InvoiceLine il
    JOIN Track t ON il.TrackId = t.TrackId
    JOIN Album al ON t.AlbumId = al.AlbumId
    JOIN Artist ar ON al.ArtistId = ar.ArtistId
    GROUP BY ar.ArtistId
)
SELECT *
FROM ArtistRevenue
ORDER BY Revenue DESC
LIMIT 1;

-- 9. Monthly revenue trend
SELECT 
    DATE_FORMAT(InvoiceDate, '%Y-%m') AS Month,
    SUM(Total) AS MonthlyRevenue
FROM Invoice
GROUP BY Month
ORDER BY Month;

-- 10. Number of customers supported by each employee
SELECT 
    e.FirstName,
    e.LastName,
    COUNT(c.CustomerId) AS CustomerCount
FROM Employee e
LEFT JOIN Customer c
ON e.EmployeeId = c.SupportRepId
GROUP BY e.EmployeeId
ORDER BY CustomerCount DESC;
