

/* =======================
   1. INNER JOIN
   ======================= */
/* Get customer names with their invoice details */

SELECT 
    c.CustomerId,
    c.FirstName,
    c.LastName,
    i.InvoiceId,
    i.InvoiceDate,
    i.Total
FROM customers c
INNER JOIN invoices i
    ON c.CustomerId = i.CustomerId;


/* =======================
   2. LEFT JOIN
   ======================= */
/* Get all customers, even if they have no invoices */

SELECT 
    c.CustomerId,
    c.FirstName,
    c.LastName,
    i.InvoiceId,
    i.Total
FROM customers c
LEFT JOIN invoices i
    ON c.CustomerId = i.CustomerId;


/* =======================
   3. RIGHT JOIN
   ======================= */
/* Get all invoices, even if customer data is missing */

SELECT 
    c.FirstName,
    c.LastName,
    i.InvoiceId,
    i.Total
FROM customers c
RIGHT JOIN invoices i
    ON c.CustomerId = i.CustomerId;


/* =======================
   4. JOIN with WHERE clause
   ======================= */
/* Customers from India and their invoices */

SELECT 
    c.FirstName,
    c.LastName,
    c.Country,
    i.InvoiceId,
    i.Total
FROM customers c
INNER JOIN invoices i
    ON c.CustomerId = i.CustomerId
WHERE c.Country = 'India';


/* =======================
   5. JOIN with AGGREGATION
   ======================= */
/* Total revenue generated by each country */

SELECT 
    c.Country,
    SUM(i.Total) AS TotalRevenue
FROM customers c
INNER JOIN invoices i
    ON c.CustomerId = i.CustomerId
GROUP BY c.Country
ORDER BY TotalRevenue DESC;


/* =======================
   6. MULTIPLE TABLE JOIN
   ======================= */
/* Invoice details with track names */

SELECT 
    i.InvoiceId,
    t.Name AS TrackName,
    il.UnitPrice,
    il.Quantity
FROM invoices i
INNER JOIN invoice_items il
    ON i.InvoiceId = il.InvoiceId
INNER JOIN tracks t
    ON il.TrackId = t.TrackId;


/* =======================
   7. CUSTOMER PURCHASE DETAILS
   ======================= */
/* Customer name with tracks they purchased */

SELECT 
    c.FirstName,
    c.LastName,
    t.Name AS TrackName
FROM customers c
INNER JOIN invoices i
    ON c.CustomerId = i.CustomerId
INNER JOIN invoice_items il
    ON i.InvoiceId = il.InvoiceId
INNER JOIN tracks t
    ON il.TrackId = t.TrackId;


/* =======================
   8. ARTIST SALES ANALYSIS
   ======================= */
/* Total sales per artist */

SELECT 
    ar.Name AS ArtistName,
    SUM(il.UnitPrice * il.Quantity) AS Revenue
FROM artists ar
INNER JOIN albums al
    ON ar.ArtistId = al.ArtistId
INNER JOIN tracks t
    ON al.AlbumId = t.AlbumId
INNER JOIN invoice_items il
    ON t.TrackId = il.TrackId
GROUP BY ar.Name
ORDER BY Revenue DESC;


/* =======================
   9. EMPLOYEE & CUSTOMER
   ======================= */
/* Support representative and their customers */

SELECT 
    e.FirstName AS EmployeeFirstName,
    e.LastName AS EmployeeLastName,
    c.FirstName AS CustomerFirstName,
    c.LastName AS CustomerLastName
FROM employees e
LEFT JOIN customers c
    ON e.EmployeeId = c.SupportRepId;


/* =======================
   10. CUSTOMER COUNT PER EMPLOYEE
   ======================= */
/* Number of customers handled by each employee */

SELECT 
    e.FirstName,
    e.LastName,
    COUNT(c.CustomerId) AS TotalCustomers
FROM employees e
LEFT JOIN customers c
    ON e.EmployeeId = c.SupportRepId
GROUP BY e.EmployeeId;


/* =======================
   11. TOP CUSTOMERS BY SPENDING
   ======================= */
/* Top 5 customers by total invoice amount */

SELECT 
    c.FirstName,
    c.LastName,
    SUM(i.Total) AS TotalSpent
FROM customers c
INNER JOIN invoices i
    ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId
ORDER BY TotalSpent DESC
LIMIT 5;


/* =======================
   12. GENRE WISE SALES
   ======================= */
/* Total revenue per music genre */

SELECT 
    g.Name AS Genre,
    SUM(il.UnitPrice * il.Quantity) AS Revenue
FROM genres g
INNER JOIN tracks t
    ON g.GenreId = t.GenreId
INNER JOIN invoice_items il
    ON t.TrackId = il.TrackId
GROUP BY g.Name
ORDER BY Revenue DESC;
